### ISSUE TITLE
可以看一下这个

### ISSUE THREAD

**Issue by jserme** [leoner/iputil#1]
https://github.com/cnwhy/lib-qqwry

**Comment by leoner** [comment]
恩, 看了呀, 但是发现和我们的 ip 库处理规则不一致呀, 就只能按照我们的规则重新实现一遍呀.

**Comment by jserme** [comment]
呃，我觉得可以http请求这个 http://ip.taobao.com/
它限制了请求次数，不知道内部可以申请一下不限制不

**Comment by leoner** [comment]
恩, 我们内部已经维护了一个 20M 的 ip 库呀.  原来是用 java 处理的, 所以这次改成 nodejs 版本了呀.
